# Generated by Django 5.1.7 on 2025-04-14 16:15

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_dash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_head', models.ImageField(blank=True, null=True, upload_to='postings')),
                ('slug', models.SlugField(default='default-slug', max_length=250, unique_for_date='post_date')),
                ('post_title', models.CharField(max_length=255)),
                ('post_content', django_ckeditor_5.fields.CKEditor5Field(default='Default body')),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
    ]
