# Generated by Django 5.1.7 on 2025-04-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_admin_dash'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_dash',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
