# Generated by Django 5.1.7 on 2025-04-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_admin_dash_video_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_dash',
            old_name='video_file',
            new_name='video_head',
        ),
        migrations.AddField(
            model_name='admin_dash',
            name='post_type',
            field=models.CharField(choices=[('image', 'Image Post'), ('video', 'Video Post')], default='image', max_length=5),
        ),
        migrations.AlterField(
            model_name='admin_dash',
            name='image_head',
            field=models.ImageField(blank=True, null=True, upload_to='postings/'),
        ),
    ]
