# Generated by Django 5.1.7 on 2025-04-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_video_file_admin_dash_video_head_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_dash',
            name='image_credit',
            field=models.CharField(default='Null', max_length=255),
        ),
    ]
