# Generated by Django 5.1.7 on 2025-04-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_admin_dash_image_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_dash',
            name='image_credit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
