# Generated by Django 5.0.6 on 2025-07-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_admin_dash_image_credit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_dash',
            name='image_credit',
        ),
        migrations.AddField(
            model_name='admin_dash',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
