# Generated by Django 5.0.6 on 2025-07-01 21:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_admin_dash_image_credit_admin_dash_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_dash',
            name='liked_by',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='admin_dash',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
