# Generated by Django 5.0.6 on 2025-07-01 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_admin_dash_liked_by_alter_admin_dash_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
